### PR TITLE
Little update for the project

### PR DESCRIPTION
**Pull request by p4535992**
Hello sorry for the inconvenience I wanted to know if this form was abandoned or if you were going to take it back in hand.

I would like to make some small changes in the future (when I have some time) if it is not a problem could you put me as a contributor to the project? Thanks.

In the meantime I put you this PR with a small update that creates a dist folder for the releases to avoid loading the README files on the server which only take up space and add prettier.

Greetings.

### CODE REVIEW

**Comment by p4535992** [comment]
Hi sorry to bother @VTTAssets could you let me know for this PR? I don't know how many people are usign this module, but I wanted to try to update it. Ty.

**Comment by VTTAssets** [comment]
Iconizer per se is used internally, but not as a standalone module by me any longer. Are you interested in becoming a maintainer of this version?

**Comment by p4535992** [comment]
Yes if it were possible I would like to try to be a contributor to the project (without creating new forks) if it is not a problem for you. I don't think I will ever have time to keep the project continuously, but in the meantime with this PR I try to combine the various bug fixes of different people who have worked on it.
Maybe in the future for foundry version 0.9.0 I could try to integrate something.

**Comment by VTTAssets** [comment]
> Yes if it were possible I would like to try to be a contributor to the project (without creating new forks) if it is not a problem for you. I don't think I will ever have time to keep the project continuously, but in the meantime with this PR I try to combine the various bug fixes of different people who have worked on it.
> Maybe in the future for foundry version 0.9.0 I could try to integrate something.

Splendid - I just invited yo in to be a collaborator to this repository, as your time allows. Thank you for your contributions

**Pull request merged**
